# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36832e5734b2afdb68c5f6145ccf2aebbc0356b09e4a740df4fbf5fd82438f6ec5986ed4952a0a233b7944642eb28a1f000c977513ae95723775c4b5697358e6

test:
  secret_key_base: 275873962d5372847708e7f3423318e10c4b6d1113f3033e8339e1b1af82dc2c49998293b1087273b994e6528e089062a3f91331158f9c3cf3c3da0616a57c9e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
